exports.candidates = ["Trump", "Clinton", "Johnson", "Stein"]

exports.candidateColors =
  'Trump': r: 255, g: 0, b: 0
  'Clinton': r: 0, g: 0, b: 255
  'Johnson': r: 255, g: 255, b: 0
  'Stein': r: 0, g: 255, b: 0

exports.databaseCollections = [
  'national_polls'
  'state_polls'
  'state_distributions'
  'results'
]

exports.stateAbbreviations =
  'Alaska': 'ak'
  'Delaware': 'de'
  'District of Columbia': 'dc'
  'Montana': 'mt'
  'North Dakota': 'nd'
  'South Dakota': 'sd'
  'Vermont': 'vt'
  'Wyoming': 'wy'
  'Hawaii': 'hi'
  'Idaho': 'id'
  'Maine': 'me'
  'New Hampshire': 'nh'
  'Rhode Island': 'ri'
  'Nebraska': 'ne'
  'New Mexico': 'nm'
  'West Virginia': 'wv'
  'Arkansas': 'ar'
  'Iowa': 'ia'
  'Kansas': 'ks'
  'Mississippi': 'ms'
  'Nevada': 'nv'
  'Utah': 'ut'
  'Connecticut': 'ct'
  'Oklahoma': 'ok'
  'Oregon': 'or'
  'Kentucky': 'ky'
  'Louisiana': 'la'
  'Alabama': 'al'
  'Colorado': 'co'
  'South Carolina': 'sc'
  'Maryland': 'md'
  'Minnesota': 'mn'
  'Missouri': 'mo'
  'Wisconsin': 'wi'
  'Arizona': 'az'
  'Indiana': 'in'
  'Massachusetts': 'ma'
  'Tennessee': 'tn'
  'Washington': 'wa'
  'Virginia': 'va'
  'New Jersey': 'nj'
  'North Carolina': 'nc'
  'Georgia': 'ga'
  'Michigan': 'mi'
  'Ohio': 'oh'
  'Illinois': 'il'
  'Pennsylvania': 'pa'
  'Florida': 'fl'
  'New York': 'ny'
  'Texas': 'tx'
  'California': 'ca'